@startuml

|#Bisque|user| Пользователь
|#Beige|system| Система
|#AntiqueWhite|db| База данных

|user|
start
if (Просмотр доступных заданий) is (Задание выбрано) then
    |system|
    :Закрепить задание за пользователем;

    |db|
    :Сохранить информацию о выбранном задании;

    |system|
    :Уведомить пользователя о взятом задании;

    |user|
    repeat
        :Выполнение игрового действия;
        
        |system|
        :Проанализировать действие пользователя;

        if (Действие соответствует условию задания?) is (Да) then
            |db|
            :Сохранить прогресс пользователя;

            |system|
            :Обновить визуальное представление прогресса задания;
        else (Нет)
        endif
    repeat while (Задание выполнено?) is (Нет) not (Да)

    |system|
    :Начислить награду;

    |db|
    :Сохранить награду пользователя;

    |system|
    :Уведомить пользователя о завершенном задании;

else (Задание не выбрано)

endif
stop

@enduml