@startuml
title Диаграмма последовательности выполнения задания

actor "Пользователь" as User
control "Система" as System
database "База данных" as DB

alt Пользователь выполняет задание

loop Пока задание не выполнено

User --> System: Выполнить игровое действие
activate System
System -> System: Проанализировать действие пользователя

opt Действие соответствует условию задания
System -> System: Рассчитать прогресс на основе действия пользователя
System ->> DB: Сохранить прогресс пользователя
activate DB
DB -->> System: Ок
deactivate DB
System --> User: Уведомить о прогрессе выполнения задания
end

opt Действие привело к завершению задания
System -> System: Рассчитать награду
System -> System: Начислить награду пользователю
System ->> DB: Сохранить награду пользователя
activate DB
DB -->> System: Ок
deactivate DB
System ->> DB: Завершить задание пользователя
activate DB
DB -->> System: Ок
deactivate DB
System --> User: Уведомить о завершении задания и начислении награды
deactivate System
end

end

deactivate System

else Пользователь отменяет задание
User --> System: Отменить задание
activate System
System ->> DB: Завершить задание пользователя
activate DB
DB -->> System: Ок
deactivate DB
System --> User: Уведомить о завершении задания
deactivate System

else Превышено ограничение выполнения задания по времени
System ->> DB: Завершить задание пользователя
activate DB
DB -->> System: Ок
deactivate DB
System --> User: Уведомить о завершении задания
deactivate System

end
@enduml
