@startuml

skinparam classAttributeIconSize 0

title Диаграмма классов

enum "Роль пользователя" {
    ИГРОК
    АДМИНИСТРАТОР
}

class Пользователь {
    - Никнейм: string
    - Пароль: string
    - Электронная почта: string
    - Роль: Роль пользователя
}

class "Канал сообщений" {
    - Название: string
}

class "Сообщение" {
    - Текст: string
    - Дата публикации: datetime
    - Отправитель: Пользователь
}

enum "Тип задания" {
    ПОСЕЩЕНИЕ МЕСТА
    ПРЕОДОЛЕНИЕ РАССТОЯНИЯ
    ДОБЫЧА РЕСУРСА
    УБИЙСТВО ПРОТИВНИКА
}

class Задание {
    - Название: string
    - Описание: string
    - Дата начала: datetime
    - Дата окончания: datetime
}

class Инвентарь {
    - Количество предмета: int
}

class "Игровой предмет" {
    - Название: string
    - Описание: string
}

Пользователь "1" -- "0..*" "Канал сообщений" : "Состоит в" >
"Канал сообщений" "1" -- "0..*" Сообщение : "Содержит" >

Пользователь "1" -- "0..*" Задание : "Принимает" >
Задание +-- "Тип задания"

Пользователь +-- "Роль пользователя" : "Обладает" >
Пользователь -- Инвентарь : "Принадлежит" <

Инвентарь "1" -- "0..*" "Игровой предмет": "Хранит" >

@enduml