@startuml

title Диаграмма базы данных

entity Пользователь {
  * идентификатор: целое
  никнейм: строка
  пароль: строка
  электронная_почта: строка
  роль: строка
}

entity Персонаж {
  * идентификатор: целое
  * пользователь_идентификатор: целое
  имя: строка
  текущаяШирота: вещественное
  текущаяДолгота: вещественное
  здоровье: целое
  мана: целое
}

entity ИсторияЛокаций {
  * идентификатор: целое
  * персонаж_идентификатор: целое
  широта: вещественное
  долгота: вещественное
  дата: дата_время
}

entity Предмет {
  * идентификатор: целое
  * персонаж_идентификатор: целое
  название: строка
  тип: строка
  количество: целое
  экипирован: логическое
}

entity Ресурс {
  * идентификатор: целое
  название: строка
  тип: строка
  широта: вещественное
  долгота: вещественное
  количество: целое
}

entity Монстр {
  * идентификатор: целое
  широта: вещественное
  долгота: вещественное
  здоровье: целое
  атака: целое
  защита: целое
  тип: строка
}

entity ИсторияСражений {
  * идентификатор: целое
  * персонаж_идентификатор: целое
  * монстр_идентификатор: целое
  дата: дата_время
  результат: строка
}

entity ИсторияСбораРесурсов {
  * идентификатор: целое
  * персонаж_идентификатор: целое
  * ресурс_идентификатор: целое
  дата: дата_время
}

Пользователь ||--o{ Персонаж : создает
Персонаж ||--o{ ИсторияЛокаций : имеет
Персонаж ||--o{ Предмет : имеет
Персонаж ||--o{ ИсторияСражений : сражается
Персонаж ||--o{ ИсторияСбораРесурсов : собирает
Ресурс -- ИсторияСбораРесурсов : собран
Монстр -- ИсторияСражений : сражается

@enduml