@startuml

title Диаграмма классов

class ИгровойДвижок {
  - игроки: Список<Игрок>
  - монстры: Список<Монстр>
  - предметы: Список<Предмет>
  - генераторРесурсов: ГенераторРесурсов
  + запуститьИгру(): void
  + обновитьИгру(): void
  + обработатьИзменениеГеолокации(игрок: Игрок, локация: Локация): void
}

class Игрок {
  - идентификатор: целое
  - имя: строка
  - текущаяЛокация: Локация
  - историяЛокаций: Список<Локация>
  - здоровье: целое
  - мана: целое
  - инвентарь: Инвентарь
  - экипировка: Экипировка
  + переместиться(локация: Локация): void
  + собратьПредмет(предмет: Предмет): void
  + атаковатьМонстра(монстр: Монстр): void
}

class Инвентарь {
  - предметы: Список<Предмет>
  + добавитьПредмет(предмет: Предмет): void
  + удалитьПредмет(предмет: Предмет): void
}

class Экипировка {
  - слоты: Карта<строка, Предмет>
  + экипироватьПредмет(предмет: Предмет): void
  + снятьПредмет(слот: строка): void
}

class Предмет {
  - идентификатор: целое
  - локация: Локация
  - название: строка
  - тип: строка
  - атрибуты: Карта<строка, целое>
  + использовать(игрок: Игрок): void
}

class Монстр {
  - идентификатор: целое
  - локация: Локация
  - здоровье: целое
  - атака: целое
  - защита: целое
  + атаковатьИгрока(игрок: Игрок): void
}

class ГенераторРесурсов {
  + запуститьГенерациюРесурсов(): void
}

class Локация {
  - широта: вещественное
  - долгота: вещественное
  + равны(другаяЛокация: Локация): boolean
  + расстояниеДоДругойЛокации(другаяЛокация: Локация): вещественное
}

ИгровойДвижок "1" -- "*" Игрок : управляет
ИгровойДвижок "1" -- "*" Монстр : управляет
ИгровойДвижок "1" -- "*" Предмет : управляет
ИгровойДвижок -- ГенераторРесурсов : использует
Игрок -- Инвентарь : имеет
Игрок -- Экипировка : имеет
Предмет -- Локация : имеет
Монстр -- Локация : имеет

@enduml
