@startuml
skinparam classAttributeIconSize 0

title Диаграмма классов

enum "Роль пользователя" {
ИГРОК
АДМИНИСТРАТОР
}

class Пользователь {
- Никнейм: string
- Пароль: string
- Электронная почта: string
- Роль: Роль пользователя
+ Войти в систему()
+ Восстановление пароля()
+ Выйти из системы()
}

class Игрок {

}


class Геолокация {
- Широта: float
- Долгота: float
+ ВычислитьРасстояние()
}

class "Характеристики игрока" {
- Уровень : float
- Здоровье: float
- Сила атаки: float
- Шанс критического удара: float
- Критический урон: float
}

class Администратор {

}

class "Менеджер заданий" {
- Задание: Задание
+ Создать()
+ Изменить()
+ Удалить()
+ Завершить()
+ Получить список(): List<Задание>
}

class "Менеджер игрового магазина" {
- Игровой магазин: Игровой магазин
+ Добавить предмет()
+ Удалить предмет()
+ Получить список(): List<Предмет>
}

class "Менеджер пользователей" {
- Пользователь: Пользователь
+ Изменить()
+ Удалить()
+ Заблокировать()
+ Разблокировать()
+ Получить список(): List<Пользователь>
}

class "Игровой магазин" {
- Название: string
- Описание: string
+ Купить()
}

enum "Тип задания" {
УЧАСТИЕ В МЕРОПРИЯТИИ
ПОСЕЩЕНИЕ МЕСТА
ПРЕОДОЛЕНИЕ РАССТОЯНИЯ
ДОБЫЧА РЕСУРСА
УБИЙСТВО ПРОТИВНИКА
}

class Задание {
- Название: string
- Описание: string
- Дата начала: datetime
- Дата окончания: datetime
}

class Инвентарь {
- Количество предмета: int
}

class "Игровой предмет" {
- Название: string
- Описание: string
+ Использовать()
+ Продать()
}

Пользователь <|-- Игрок
Пользователь <|-- Администратор

Администратор o-- "Менеджер заданий"
Администратор o-- "Менеджер пользователей"
Администратор o-- "Менеджер игрового магазина"

Игрок "1" -- "*" Задание
Задание +-- "Тип задания"

Игрок "1" -- "*" Геолокация

Игрок -- Инвентарь
Инвентарь "1" -- "*" "Игровой предмет"

Игрок -- "Игровой магазин"
"Игровой магазин" "1" -- "*" "Игровой предмет"

Игрок *-- "Характеристики игрока"
@enduml
